### PR TITLE
comparison of new and old results

### PR DESCRIPTION
**Pull request by kweav**
Expanding on the review of the GI Mapping and gimap results given the new code changes. 

Haven't added a correlation metric because it's just a blob of points for GI scores

### CODE REVIEW

**Comment by kweav** [comment]
@cansavvy requested review is verification that I'm using the results correctly, making the intended/correct comparisons for the resulting dataset

**Comment by cansavvy** [comment]
Screenshot 2024-11-13 at 9 51 49 AM


@kweav This honestly looks pretty darn good. My only question is why it looks like there's like a couple different lines the points lie on for this correlation? Do you see that? Wondering if there's a pattern we should look into?

**Comment by cansavvy** [comment]
It's probably even more clear with the GI correlation: 
download

It's not necessarily bad, just peculiar and we might want to see if there's a pattern there.

**Comment by kweav** [comment]
Those are the Log fold change comparisons. I just had to make edits to the file to get it to render again since the pipeline had a few changes since I last made the comparisons

**Comment by kweav** [comment]
> My only question is why it looks like there's like a couple different lines the points lie on for this correlation? Do you see that? Wondering if there's a pattern we should look into?

Yes, I see that pattern too, and I remember us seeing it last time as well. Not really sure why there are a couple different lines. I could try to color based off some sort of feature...target_type, rep, something like that?

**Pull request merged**
